CREATE TABLE Cities2 (
  Id INT IDENTITY PRIMARY KEY NOT NULL,
  [Name] NVARCHAR(20) NOT NULL ,
  CountryCode CHAR(2) NOT NULL,

  -- CONSTRAINT chk_Cities_CountryCode CHECK (LEN(CountryCode) = 2)
)

CREATE TABLE Hotels (
  Id INT IDENTITY PRIMARY KEY NOT NULL,
  [Name] NVARCHAR(30) NOT NULL,
  CityId INT NOT NULL FOREIGN KEY REFERENCES Cities(Id),
  EmployeeCount INT NOT NULL,
  BaseRate DECIMAL(15, 2)
)

CREATE TABLE Rooms (
  Id INT IDENTITY PRIMARY KEY NOT NULL,
  Price DECIMAL(15, 2) NOT NULL,
  Type NVARCHAR(20) NOT NULL,
  Beds INT NOT NULL,
  HotelId INT NOT NULL FOREIGN KEY REFERENCES Hotels(Id)
)

CREATE TABLE Trips (
  Id INT IDENTITY PRIMARY KEY NOT NULL,
  RoomId INT NOT NULL FOREIGN KEY REFERENCES Rooms(Id),
  BookDate DATE NOT NULL,
  ArrivalDate DATE NOT NULL,
  ReturnDate DATE NOT NULL,
  CancelDate DATE,

  CONSTRAINT chk_Trips_BookDate CHECK (BookDate < ArrivalDate),
  CONSTRAINT chk_Trips_ArrivalDate CHECK (ArrivalDate < ReturnDate),
)

CREATE TABLE Accounts (
  Id INT IDENTITY PRIMARY KEY NOT NULL,
  FirstName NVARCHAR(50) NOT NULL,
  MiddleName NVARCHAR(20),
  LastName NVARCHAR(50) NOT NULL,
  CityId INT NOT NULL FOREIGN KEY REFERENCES Cities(Id),
  BirthDate DATE NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE AccountsTrips (
  AccountId INT NOT NULL FOREIGN KEY REFERENCES Accounts(Id),
  TripId INT NOT NULL FOREIGN KEY REFERENCES Trips(Id),
  Luggage INT NOT NULL CHECK (Luggage >= 0)
)